config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :coaches, only: [:index,:new]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
  has_many :speciality_coaches
  has_many :specialities, through: :speciality_coaches
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'メッセージを送ってみましょう！'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_many :speciality_coaches
  has_many :coaches, through: :speciality_coaches
end

app/models/speciality_coach.rb
class SpecialityCoach < ApplicationRecord
  belongs_to :coach
  belongs_to :speciality
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
  end

  def new
    @coach = Coach.new
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    # binding.pry
    if @group.save
      # binding.pry
      redirect_to group_messages_path(@group.id)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/coaches/_main_chat_coach.html.haml
.coaches
  .coach-section
    %p.info クリックするとレッスンプロの詳細を確認することができます。
    %p.info さらに各レッスンプロの体験レッスンページより体験レッスンを申し込むことができます。
  .coach-list
    -# ここにaタグが入る
    .coach-title
      %h.coach-name 近藤 はるかプロ
      %p アカデミー担当インストラクター
    .coach-user
      .recommend
        %h おすすめ度 ⭐️
      .coach-img
        = image_tag "coach1.jpg", size: "300x315", alt: "coach"
      .coach-text
        .tag-box
          %p.tag-user1 体験レッスン
          %p.tag-user2 初心者向け
          %p.tag-user3 コースレッスン
          .catch-titile
            %h 勝つゴルフレッスンで、スコアを縮めます！！
          %p.minute これまで日米で学んできた知識を生かしていろいろなことをシンプルに出来るよう指導し、皆様の個々の目標が達成できるようにお手伝いしてまいります。そして“ゴルフは楽しい！！”と思ってもらえたらとてもうれしく思います。
          %p.adress メンタル改善
          %p.acsess 指導者育成
        .coach-box
          %h.cupon お得なレッスンチケット一覧
          .box-ticket
            %p.box-ticket-titile 体験レッスン
            %p.box-ticket-tag 無料体験レッスン1回 50分無料
    .coach-title
      %h.coach-name 近藤 はるかプロ
      %p アカデミー担当インストラクター
    .coach-user
      .recommend
        %h おすすめ度 ⭐️
      .coach-img
        = image_tag "coach1.jpg", size: "300x315", alt: "coach"
      .coach-text
        .tag-box
          %p.tag-user1 体験レッスン
          %p.tag-user2 初心者向け
          %p.tag-user3 コースレッスン
          .catch-titile
            %h 川越ICから10分！！24時間お好きな時間で練習可能☆レッスンも夜22:00まで◎
          %p.minute 初めての方も大歓迎！！習い放題月額5,980円からのゴルフスクール。365日練習できる！なんと24時間営業！！室内の快適な環境で、ご自身のプランに合わせた形で思う存分練習ができます！認定コーチによるレッスンと全打席最新解析機で練習をフルサポート。的確なコーチングを受けて着実にレベルアップしたい、という方にピッタリの練習環境をご提供します。
          %p.adress 〒157-0072 東京都世田谷区祖師谷4-2-11 ビッグA入り口2階
          %p.acsess 川越ICから車で10分
        .coach-box
          %h.cupon お得なレッスンチケット一覧
          .box-ticket
            %p.box-ticket-titile 体験レッスン
            %p.box-ticket-tag 無料体験レッスン1回 50分無料
    .coach-title
      %h.coach-name 近藤 はるかプロ
      %p アカデミー担当インストラクター
    .coach-user
      .recommend
        %h おすすめ度 ⭐️
      .coach-img
        = image_tag "coach1.jpg", size: "300x315", alt: "coach"
      .coach-text
        .tag-box
          %p.tag-user1 体験レッスン
          %p.tag-user2 初心者向け
          %p.tag-user3 コースレッスン
          .catch-titile
            %h 川越ICから10分！！24時間お好きな時間で練習可能☆レッスンも夜22:00まで◎
          %p.minute 初めての方も大歓迎！！習い放題月額5,980円からのゴルフスクール。365日練習できる！なんと24時間営業！！室内の快適な環境で、ご自身のプランに合わせた形で思う存分練習ができます！認定コーチによるレッスンと全打席最新解析機で練習をフルサポート。的確なコーチングを受けて着実にレベルアップしたい、という方にピッタリの練習環境をご提供します。
          %p.adress 〒157-0072 東京都世田谷区祖師谷4-2-11 ビッグA入り口2階
          %p.acsess 川越ICから車で10分
        .coach-box
          %h.cupon お得なレッスンチケット一覧
          .box-ticket
            %p.box-ticket-titile 体験レッスン
            %p.box-ticket-tag 無料体験レッスン1回 50分無料







-# .message
-#   .upper-message
-#     .upper-message__user-name
-#       = message.user.name
-#     .upper-message__date
-#       = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
-#   .lower-message
-#     - if message.content.present?
-#       %p.lower-message__content
-#         = message.content
-#     = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/coaches/_right_bar_coach.html.haml
.pro-content
  .pro-profile
    .pro-text-top
      %h.pro-text-top-on プロフィール
    .pro-apalel
      .pro-img
        = image_tag "coach1.jpg", size: "150x157", alt: "coach"
      .pro-text
        %p.point-name 近藤はるかプロの一番の強み
        %p.strong 勝つゴルフレッスンで、<br>スコアを縮めます！！
        .box-wrapper__tongari
  .pro-profile-top
    .pro-profile-top-on
      %h.pro-top 誕生日
    %p.p-top 1981年 京都市生まれ
  .pro-profile-1st
    .pro-profile-top-on1st
      %h.pro-top 実績
    %p.p-top 現在PGAティーチングプロA級
    %p JGTO認定コーチ
    %p プロボクシングA級ライセンス
    %p ミズノプロサポートスタッフ
  .pro-profile-2nd
    .pro-profile-top-on2
      %h.pro-top 対応ゴルフ場
    %p.p-top ノーザンカントリークラブ錦ヶ原ゴルフ場
    %p 上里ゴルフ場
    %p アコーディア・ゴルフ習志野カントリークラブ
    %p かずさカントリークラブ
    %p ABCいすみゴルフコース
  .pro-profile-3rd
    .pro-profile-top-on3
      %h.pro-top 特徴
    %p.p-top 個人レッスン
    %p ラウンドレッスン
    %p 指導者育成
    %p メンタル改善
  .pro-profile-4th
    .pro-profile-top-on4
      %h.pro-top 定休日
    %p.p-top 月・木
    %p 幅広く対応できますのでご相談ください
  .pro-profile-5th
    .pro-profile-top-on5
      %h.pro-top 経歴
    %p.p-top これまで日米で学んできた知識を生かしていろいろなことをシンプルに出来るよう指導し、皆様の個々の目標が達成できるようにお手伝いしてまいります。そして“ゴルフは楽しい！！”と思ってもらえたらとてもうれしく思います。

app/views/coaches/_side_bar_coach.html.haml
.side-bar-coach
  .side-bar-list
    %ul.area
      %li 
        北海道・東北
        %p
          北海道 | 青森県 | 岩手県 | 秋田県 
        %p 
          宮城県 | 山形県 | 福島県
      %li 
        関東
        %p 
          東京都 | 神奈川県 | 千葉県 | 埼玉県
        %p 
          茨城県 | 栃木県 | 群馬県
      %li
        北陸・甲信越
        %p
          山梨県 | 長野県 | 新潟県 | 富山県 
        %p 
          石川県 | 福井県
      %li
        中部
        %p 愛知県 | 静岡県 | 三重県 | 岐阜県
      %li
        関西
        %p 大阪府 | 和歌山県 | 京都府 | 滋賀県 
        %p 兵庫県 | 奈良県
      %li
        中国
        %p 広島県 | 山口県 | 岡山県 | 鳥取県 
        %p 島根県
      %li
        四国
        %p 徳島県 | 香川県 | 愛媛県 | 高知県
      %li
        九州
        %p 福岡県 | 佐賀県 | 長崎県 | 大分県 
        %p 熊本県 | 宮崎県 | 鹿児島県
      %li 
        沖縄
        %p 沖縄県



-# .side-bar
-#   .side-bar__groups-list
-#   - current_user.groups.each do |group|
-#     .group
-#       = link_to group_messages_path(group) do
-#         .group__name
-#           = group.name
-#         .group__message
-#           = group.show_last_message

app/views/coaches/index.html.haml
.header
  ゴルMATCH
  .user-name
    = current_user.name + "さん"
    .header-list
      = link_to edit_user_path(current_user) do
        %h1 アカウント&リスト◁
.group-header
  .home-btn
    = link_to root_path do
      %i.fas.fa-home
    .group-edit-btn
      %h 参加中のグループ一覧
  .group-text
    %h レッスンプロ在籍一覧
.wrapper-coach
  = render "side_bar_coach"
  = render "main_chat_coach"
  = render "right_bar_coach"

.main-all
  .main-body
    .container
      .container-inner
        .container-main
          .main-content-top
            .search-head
            .search-sec
            .search-softview
            .result_list
        .container-left
.footer
  %p Copyright © 2020 ゴルMATCH Inc. All Rights Reserved.
  .footer-list
    follow us!
    = link_to "https://www.facebook.com/", class: "contents__btn" do
      = icon('fab', 'facebook-square')
    = link_to "https://twitter.com/", class: "contents__btn" do
      = icon('fab', 'twitter')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'instagram')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'youtube')

app/views/coaches/new.html.haml
.header
  ゴルMATCH
  -# .user-name
  -#   = current_user.name + "さん"
  -#   .header-list
  -#     = link_to edit_user_path(current_user) do
  -#       %h1 アカウント&リスト◁
.group-header
  -# .home-btn
  -#   = link_to root_path do
  -#     %i.fas.fa-home
  -#   .group-edit-btn
      %h 参加中のグループ一覧
  .group-text
    %h レッスンプロ登録
.coach-new-contaner
  .contaner__innner
    .sction-card
      .card__content
        %p 外部サービス側にゴルMATCHのご利用状況が投稿されることは一切ありません。
  = form_for @coach do |f|
    .new-wrapper
      .new-wrapper__main
        .new-wrapper__main__title
          プロフィール画像
          %span{class: "require"} 必須
        .new-wrapper__main__text
        
        .new-wrapper__main__image-field
          = f.label :image, class: 'input-box__text' do
            #img_field{:onclick => "$('#file').click()"}
              -# - if @coach.image.url.present?
              -#   = image_tag(@coach.image.url)
              -# - else
              -#   %i.fas.fa-image
              -#   %i.fas.fa-file-upload.add
              = icon('fas', 'image', class: 'input-box__text__image')
            = f.file_field :image, class: 'input-box__text__file', id: "file", style: "display:none;"
            .new-wrapper__main__image-field__text
              クリックしてファイルをアップロード
      .new-wrapper__main
        .new-wrapper__main__title
          現在活動されているお名前
          %span{class: "require"} 必須
        = f.text_field :name, {class: "new-wrapper__main__input-text", placeholder: "〇〇プロ"}
        .new-wrapper__main__title.spacing
          私の強み
          %span{class: "require"} 必須
        = f.text_area :profile, {class: "new-wrapper__main__input-textarea", placeholder: "40文字以内でお願い致します"}
      .new-wrapper__main
        .new-wrapper__main__subtitle
          現在までのご経歴など
        .new-wrapper__main__title
          実績
          %span{class: "require"} 必須
        = f.select :career, [["選択してください",""],"PGAティーチングプロA級","JGTO認定コーチ","その他"], {}, class: "new-wrapper__main__input-select"
        .new-wrapper__main__title.spacing
          経歴
          %span{class: "require"} 任意
        = f.text_field :comment, {class: "new-wrapper__main__input-text", placeholder: "例）日本女子オープン選手権競技出場 など"}
        .new-wrapper__main__title.spacing
          対応ゴルフ場
          %span{class: "any"} 任意
        = f.select :course, [["選択してください",""],"ノーザンカントリークラブ錦ヶ原ゴルフ場","上里ゴルフ場","アコーディア・ゴルフ習志野カントリークラブ","かずさカントリークラブ","ABCいすみゴルフコース"], {}, class: "new-wrapper__main__input-select"
      .new-wrapper__main
        .new-wrapper__main__subtitle
          専門分野
        .new-wrapper__main__title
          特徴
          %span{class: "require"} 必須
          -# = f.label :speciality
          = f.collection_check_boxes(:speciality_ids, Speciality.all, :id, :name) 
          -#   <%= specialty.label do %>
          -#     <%= specialty.check_box %>
          -#     <%= specialty.text %>
          -#   <% end %>
          -# <% end %>
          -# = f.label :specialty, 'カテゴリ' 
          -#   = f.collection_check_boxes(:specialities_ids, Specialty.all, :id, :name) do |s| 
          -#     = s.label do
          -#       = s.check_box 
          -#       = s.text 

        -# = f.select :specialty, [["選択してください",""],"個人レッスン","ラウンドレッスン","指導者育成","メンタル改善"], {}, class: "new-wrapper__main__input-select"
        .new-wrapper__main__title.spacing
          活動されている地域
          %span{class: "require"} 必須
        = f.select :course, [["選択してください",""],"北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"], {}, class: "new-wrapper__main__input-select"
        .new-wrapper__main__title.spacing
          希望する定休日
          %span{class: "require"} 必須
        = f.select :holiday, [["選択してください",""],"土・日","月・火","水・木","金・土","相談に応じて幅広く対応"], {}, class: "new-wrapper__main__input-select"
      .new-wrapper__main
        = f.submit "面談を希望する", {class:"new-wrapper__main__submit"}
        .new-wrapper__main__caution
          上記の会員規約と個人情報の取り扱いに同意した上で面談を希望するをクリックしてください。

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.header
  ゴルMATCH
  .user-name
    = current_user.name + "さん"
    .header-list
      = link_to edit_user_path(current_user) do
        %h1 アカウント&リスト◁
.group-header
  .home-btn
    = link_to root_path do
      %i.fas.fa-home
    .group-edit-btn
      %h 参加中のグループ一覧
  .group-text
    = current_user.name + "さんのレッスンスケジュール一覧"
.wrapper
  = render 'messages/side_bar'
  .plan
    <iframe src="https://calendar.google.com/calendar/b/2/embed?height=600&amp;wkst=1&amp;bgcolor=%230B8043&amp;ctz=Asia%2FTokyo&amp;src=Z29sbWF0Y2g3MjEwNkBnbWFpbC5jb20&amp;src=amEuamFwYW5lc2UjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%23039BE5&amp;color=%230B8043" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    .reservation-form
      %p 手ぶらでOKレンタル無料！今なら50分3,000円！
      .home-btn
        <div class="sam13"><a href="/groups/new">レッスンを予約する<p>新規グループチャットの作成</p></a></div>
  .right-bar-plan
    %h20 ゴルMATCH 料金プラン
    %table
      %tr 
        %th 60分✖︎月2回
        %td 12,000円 
      %tr
        %th 60分✖︎月4回
        %td 15,000円
      %tr
        %th 60分✖︎月8回
        %td 32,000円
      %tr
        %th 60分✖︎受け放題
        %td 32,000円        
      %tr
        %th マンツーマン
        %td 12,000円
      %tr
        %th 入会金
        %td 20,000円 
    = image_tag "price_campagin_01.png", size: "352x298", alt: "google" 
    
.footer
  %p Copyright © 2020 ゴルMATCH Inc. All Rights Reserved.
  .footer-list
    follow us!
    = link_to "https://www.facebook.com/", class: "contents__btn" do
      = icon('fab', 'facebook-square')
    = link_to "https://twitter.com/", class: "contents__btn" do
      = icon('fab', 'twitter')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'instagram')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'youtube')

app/views/groups/new.html.haml
.image-groups
  .main-text
    %h1 マッチング数 <span>No.1</span> 
    %h2 ゴルMATCH
    %h3 ラウンドレッスンを一緒に！
    %h4 必ず上達するマッチングアプリ
    .mobile
      = image_tag "sample_qr.gif", size: "60x60", alt: "QR"
      .sab-text
        %h5 スマートフォンから
        %h5 QRコードを読み込んでください
        %h5 ログイン後ご利用いただけます
        %h6 アプリダウンロードはこちら
        = image_tag "ja_badge_web_generic.png", size: "190x50", alt: "google" 
  .chat-group-form
    %h1 新規チャットグループを作成
    = render partial: 'form', locals: { group: @group }
    .account-page__inner--left.account-page__header
      .grouphome-btn 
        = link_to "メッセージ画面に戻る", root_path, class: 'home-btn'
.footer
  %p Copyright © 2020 ゴルMATCH Inc. All Rights Reserved.
  .footer-list
    follow us!
    = link_to "https://www.facebook.com/", class: "contents__btn" do
      = icon('fab', 'facebook-square')
    = link_to "https://twitter.com/", class: "contents__btn" do
      = icon('fab', 'twitter')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'instagram')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'youtube')

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Golmatch
    = csrf_meta_tags
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield
    

app/views/messages/_main_chat.html.haml
.messages
  = render @messages
  .form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__message', placeholder: 'ここにメッセージ内容を入力'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          = icon('fas', 'paperclip', class: 'icon')
          = f.file_field :image, class: 'hidden'
      = f.submit '送信', class: 'form__submit'

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_right_bar.html.haml
.right-bar 
  .teacher-plf
    = image_tag "HIRO_V4.jpg", size: "320x213", alt: "test"
    %h1 能力を最大限に引き出すトップコーチ
    %p トラックマンなどの弾道解析器を使ったデータ重視の的確なアドバイスが特徴。東北高校ゴルフ部のコーチも5年務めている。
    %h2 
  .place-tag
    <iframe width="320" height="213" src="https://www.youtube.com/embed/10DTvi66irY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    %p 【東京】阿河徹レッスン
    %p agalesson@yahoo.co.jp
    %p 世田谷区大蔵6-7-21 井山ゴルフ練習場
    %p 金・土・日に開講（時間は応相談）
    %p 1時間1万800円

app/views/messages/index.html.haml
.header
  ゴルMATCH
  .user-name
    = current_user.name + "さん"
    .header-list
      = link_to edit_user_path(current_user) do
        %h1 アカウント&リスト◁
.group-header
  .home-btn
    = link_to root_path do
      %i.fas.fa-home
    .group-edit-btn
      = link_to 'グループを編集', '/groups/new', class: "edit" 
  .group-text
    = @group.name
    .chat-main__group-info-member このチャットのメンバー
    - @group.users.each do |user|
      .chat-main__group-info-member
        = user.name + "さん"
.wrapper
  = render "side_bar"
  = render "main_chat"
  = render "right_bar"

.footer
  %p Copyright © 2020 ゴルMATCH Inc. All Rights Reserved.
  .footer-list
    follow us!
    = link_to "https://www.facebook.com/", class: "contents__btn" do
      = icon('fab', 'facebook-square')
    = link_to "https://twitter.com/", class: "contents__btn" do
      = icon('fab', 'twitter')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'instagram')
    = link_to "https://www.instagram.com/", class: "contents__btn" do
      = icon('fab', 'youtube')